### ISSUE TITLE
能否丰富一点平台，单平台超10次就不发了

### ISSUE THREAD

**Issue by AZhanGGGGG** [xiaoxuan6/SMSBombing#10]
作者是真的牛逼，能否丰富一点平台，单平台超10次就不发了。

**Comment by xiaoxuan6** [comment]
> 作者是真的牛逼，能否丰富一点平台，单平台超10次就不发了。

全量轰炸

```
sms-bombing 136xxxxxxxx --num=all
```

启动 5 次,轰炸一个人的手机号(136xxxxxx), 启动循环轰炸, 轮番轰炸2次

```
sms-bombing 136xxxxxxxx --num=5 -l 2
```

等。

`README.md` 中写的还不够清楚吗？
