### ISSUE TITLE
老哥，api怎么找的？教教我

### ISSUE THREAD

**Issue by Mengmengbai** [xiaoxuan6/SMSBombing#11]
api过段时间就过期了，教教我怎么找api吧。
感谢老哥，好人一生平安

**Comment by xiaoxuan6** [comment]
> api过段时间就过期了，教教我怎么找api吧。 感谢老哥，好人一生平安

过期什么意思？提供一下报错截图


# 寻找api

访问 [fofa](https://fofa.info) 搜索条件
```
"验证码" && "手机号" && "登录"
```

**Comment by Mengmengbai** [comment]
就有有些api过段时间，就会显示time out 请求失败。我用别的SMSboom项目用一段时间api就失效了

**Comment by cy920820** [comment]
@Mengmengbai  https://t.me/qingfeng888bot?start=6684456413 试试这个，最近刚发现

**Comment by JssDream** [comment]
> > api过段时间就过期了，教教我怎么找api吧。 感谢老哥，好人一生平安
> 
> 过期什么意思？提供一下报错截图
> 
> # 寻找api
> 访问 [fofa](https://fofa.info) 搜索条件
> 
> ```
> "验证码" && "手机号" && "登录"
> ```
可以的，还有这东西呐
