### ISSUE TITLE
使用sms-bombing 命令后无反应

### ISSUE THREAD

**Issue by ShiningShirley** [xiaoxuan6/SMSBombing#22]
![sms](https://github.com/xiaoxuan6/SMSBombing/assets/45312279/bba21c92-9619-46ae-b657-2c605557d0bc)

**Comment by ShiningShirley** [comment]
![sms1](https://github.com/xiaoxuan6/SMSBombing/assets/45312279/c272eea9-ffae-4730-94ff-015d8f033e9c)

**Comment by xiaoxuan6** [comment]
> ![sms](https://private-user-images.githubusercontent.com/45312279/329682867-bba21c92-9619-46ae-b657-2c605557d0bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0ODU4OTgsIm5iZiI6MTcxNTQ4NTU5OCwicGF0aCI6Ii80NTMxMjI3OS8zMjk2ODI4NjctYmJhMjFjOTItOTYxOS00NmFlLWI2NTctMmM2MDU1NTdkMGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDAzNDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNDUxZWZkZTg3MWQ0YTVlODBiZjVjOWNkZmQ3YmJhYTNlZDMzYzYzNjUwMWNmMzg3OTA1M2VmYzNkMzI0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1IOiLl7Tp_xTUdrF--XWPzGWgokoy2zO-BXu9BTmvq4)

在输入框光标位置输入手机号

[相关操作](https://github.com/xiaoxuan6/SMSBombing#use)

**Comment by ShiningShirley** [comment]
![sms2](https://github.com/xiaoxuan6/SMSBombing/assets/45312279/3c68d857-db1c-4140-a149-dc9670e4b71b)
一直卡在这了
