### ISSUE TITLE
这命令用不了

### ISSUE THREAD

**Issue by SamWang8888** [xiaoxuan6/SMSBombing#24]
![image](https://github.com/xiaoxuan6/SMSBombing/assets/119713630/fc6b916a-5091-4409-853c-dcf82995e962)
![111](https://github.com/xiaoxuan6/SMSBombing/assets/119713630/54b045ea-c3a5-47ed-8b25-2d4bb0468c88)
安装了 没有这命令用

**Comment by xiaoxuan6** [comment]
> ![image](https://private-user-images.githubusercontent.com/119713630/332071570-fc6b916a-5091-4409-853c-dcf82995e962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTAyNjcsIm5iZiI6MTcxNjIwOTk2NywicGF0aCI6Ii8xMTk3MTM2MzAvMzMyMDcxNTcwLWZjNmI5MTZhLTUwOTEtNDQwOS04NTNjLWRjZjgyOTk1ZTk2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMjU5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTAyY2IzNWI3YTEzMjU5OWNjMmMzYmNjYmJmYzE1OTkwYWM1MmM1ZmFmNTBlNzc4M2ExYWNkNDEzNWI4M2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.17F7BNgZHZad1-jpOlc0evcUc1CX7kCOMyJJmDWbVvk) ![111](https://private-user-images.githubusercontent.com/119713630/332071685-54b045ea-c3a5-47ed-8b25-2d4bb0468c88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTAyNjcsIm5iZiI6MTcxNjIwOTk2NywicGF0aCI6Ii8xMTk3MTM2MzAvMzMyMDcxNjg1LTU0YjA0NWVhLWMzYTUtNDdlZC04YjI1LTJkNGJiMDQ2OGM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMjU5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWZlZmYxNGJkNWVlOTg4YTg5MmFiZTZhNzU2Nzg1MjVmNDg0NTFmOWE4YTRkMDU0ZjcxOGZmYjBmNDVkZDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9IEo2RSuPf7q5iAGqeqcjJJ4MtgZ9k_A1ZGDW9VN8zk) 安装了 没有这命令用

方法一：将 `sms-bombing` 添加到环境变量中

方法二：在 `sms-bombing` 当前目录下使用 `./sms-bombing`

**Comment by SamWang8888** [comment]
> > ![image](https://private-user-images.githubusercontent.com/119713630/332071570-fc6b916a-5091-4409-853c-dcf82995e962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTAyNjcsIm5iZiI6MTcxNjIwOTk2NywicGF0aCI6Ii8xMTk3MTM2MzAvMzMyMDcxNTcwLWZjNmI5MTZhLTUwOTEtNDQwOS04NTNjLWRjZjgyOTk1ZTk2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMjU5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTAyY2IzNWI3YTEzMjU5OWNjMmMzYmNjYmJmYzE1OTkwYWM1MmM1ZmFmNTBlNzc4M2ExYWNkNDEzNWI4M2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.17F7BNgZHZad1-jpOlc0evcUc1CX7kCOMyJJmDWbVvk) ![111](https://private-user-images.githubusercontent.com/119713630/332071685-54b045ea-c3a5-47ed-8b25-2d4bb0468c88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTAyNjcsIm5iZiI6MTcxNjIwOTk2NywicGF0aCI6Ii8xMTk3MTM2MzAvMzMyMDcxNjg1LTU0YjA0NWVhLWMzYTUtNDdlZC04YjI1LTJkNGJiMDQ2OGM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMjU5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWZlZmYxNGJkNWVlOTg4YTg5MmFiZTZhNzU2Nzg1MjVmNDg0NTFmOWE4YTRkMDU0ZjcxOGZmYjBmNDVkZDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9IEo2RSuPf7q5iAGqeqcjJJ4MtgZ9k_A1ZGDW9VN8zk) 安装了 没有这命令用
> 
> 方法一：将 `sms-bombing` 添加到环境变量中
> 
> 方法二：在 `sms-bombing` 当前目录下使用 `./sms-bombing`
大神 
请问api.json是在哪里呀？我下载了sms 好像只有单个的文件 不知道咋修改api
