### ISSUE TITLE
脚本自动退出了。

### ISSUE THREAD

**Issue by laopaoer-wallet** [xiaoxuan6/SMSBombing#4]
![image](https://github.com/xiaoxuan6/SMSBombing/assets/75466368/ef7d1f58-243c-46ee-abed-e3e75805881a)

**Comment by xiaoxuan6** [comment]
脚本默认根据 [api](https://github.com/xiaoxuan6/SMSBombing/blob/main/api.json) 循环发送一次，全部执行完自动结束，如果想多遍历几次请设置 `LOOP=2`

**Comment by laopaoer-wallet** [comment]
> 脚本默认根据 [api](https://github.com/xiaoxuan6/SMSBombing/blob/main/api.json) 循环发送一次，全部执行完自动结束，如果想多遍历几次请设置 `LOOP=2`

api有点少咯。。
