### ISSUE TITLE
大佬帮忙看看

### ISSUE THREAD

**Issue by raogu** [xiaoxuan6/SMSBombing#7]
E:\MySoftware\SMS\SMSBoom\SMSBombing-1.4.0\bin> composer global require james.xue/sms-bombing --no-dev 
Changed current directory to C:/Users/15679/AppData/Roaming/Composer

                                         
  The "--no-dev" option does not exist.

**Comment by raogu** [comment]
> 
![微信图片_20231028012816](https://github.com/xiaoxuan6/SMSBombing/assets/115861259/7023f2f2-5d0e-4175-b925-bf2e54421fd7)

**Comment by xiaoxuan6** [comment]
> > 
> 
> ![微信图片_20231028012816](https://user-images.githubusercontent.com/115861259/278716521-7023f2f2-5d0e-4175-b925-bf2e54421fd7.png)

去掉 `--no-dev` 重新执行即可

**Comment by raogu** [comment]
![Snipaste_2023-10-28_09-19-09](https://github.com/xiaoxuan6/SMSBombing/assets/115861259/c5f965b9-af84-4699-9cd8-9eb0f23cd543)
还是不行

**Comment by raogu** [comment]
谢谢大佬，问题解决了
